FROM ruby:3.1.0-slim-bullseye

WORKDIR /home/app

COPY . .

RUN apt-get update && apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev libsqlite3-dev libyaml-dev libxml2-dev libxslt-dev libffi-dev && apt-get install -y curl && curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh && bash nodesource_setup.sh && apt-get install sqlite3 && apt-get install -y nodejs && gem install bundler:2.3.3 && bundle install && rake assets:precompile && rails db:migrate RAILS_ENV=production

EXPOSE 3000

CMD ["rails","s","-e","production"]
