version: '3.8'

services:
   
    example-frontend:
        image: example-frontend:latest
        build: ./example-frontend/
        environment:
          - REACT_APP_BACKEND_URL=http://127.0.0.1:8080
        ports:
          - "3001:5000"
        command: serve -s -l 5000 build

    example-backend:
        image: example-backend:latest
        build: ./example-backend/
        environment: 
          - PORT=8080
          - REQUEST_ORIGIN=http://127.0.0.1:3001
        ports:
          - "8080:8080"
        command: ./server
